twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        gl_app_name: '%env(APP_NAME)%'

when@test:
    twig:
        strict_variables: true
