redirect:
    path: /
    controller: App\Controller\Common\LanguageRedirectController::redirectToLocale

controllers:
    resource: ../src/Controller/
    type: annotation

    prefix: /{_locale}/
    requirements:
        _locale: '%available.locales%'
    defaults:
        _locale: '%locale%'

kernel:
    resource: ../src/Kernel.php
    type: annotation
